# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf583cde93ee02dda913a7b58aee3c061169c7092e9b7d76286dc4e876c06722f5eb34aa907a6afe762bac62ce3bda3f99128b082a38230ea658a5c1eaa5e0ba

test:
  secret_key_base: cfde8401373c8bf29a0f8ab084766990c2ecc7ed97671cfe642dd022f2f0651a837730adef868050d2967abae29c2c0fe9c89d16fb1cf52781f5c464448b4a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
